// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3dtD47y2qc64Q9jZ3CCklGxRV9Eks2GY',
    appId: '1:285368364351:web:33757e6f051b15badab78a',
    messagingSenderId: '285368364351',
    projectId: 'mychatapp-ee9c9',
    authDomain: 'mychatapp-ee9c9.firebaseapp.com',
    storageBucket: 'mychatapp-ee9c9.firebasestorage.app',
    measurementId: 'G-5Z1FWPS7MB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT1yyG-FTQhKB_rU-od_OksBkTmwWYlwQ',
    appId: '1:285368364351:android:667d7d0876fbf6c1dab78a',
    messagingSenderId: '285368364351',
    projectId: 'mychatapp-ee9c9',
    storageBucket: 'mychatapp-ee9c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB83oZ-sPlg5htHhicDrk97scI6mx6Xf80',
    appId: '1:285368364351:ios:c55d36aed37bf86adab78a',
    messagingSenderId: '285368364351',
    projectId: 'mychatapp-ee9c9',
    storageBucket: 'mychatapp-ee9c9.firebasestorage.app',
    iosBundleId: 'com.example.firebaseMychat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB83oZ-sPlg5htHhicDrk97scI6mx6Xf80',
    appId: '1:285368364351:ios:c55d36aed37bf86adab78a',
    messagingSenderId: '285368364351',
    projectId: 'mychatapp-ee9c9',
    storageBucket: 'mychatapp-ee9c9.firebasestorage.app',
    iosBundleId: 'com.example.firebaseMychat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3dtD47y2qc64Q9jZ3CCklGxRV9Eks2GY',
    appId: '1:285368364351:web:05df66714a72ad4cdab78a',
    messagingSenderId: '285368364351',
    projectId: 'mychatapp-ee9c9',
    authDomain: 'mychatapp-ee9c9.firebaseapp.com',
    storageBucket: 'mychatapp-ee9c9.firebasestorage.app',
    measurementId: 'G-LMNJD3D94P',
  );
}
